EXPERIMENT:
  NAME: ""
  TAG: "hdld,wrn_40_2,MobileNetV2_0.5_0.6"
  PROJECT: "cifar100_baselines_hdld_7"
DISTILLER:
  TYPE: "HDLD"
  TEACHER: "wrn_40_2"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
HDLD:
  ALPHA: 0.5
  BETA: 0.6